//Constantes del juego
export const GAME_CONFIG = {
  TOTAL_PREGUNTAS: 10,
  TOTAL_SKIPS: 3,
  TIEMPO_INICIAL: 60,
  BONUS_TIEMPO: 3,
  MARGEN_ERROR: 0.11,
  PUNTOS_POR_ACIERTO: 10,
  MONEDAS_POR_NIVEL: 50
};